version: '3.8'

services:
  todo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=https://80-niezleziolk-fullstackop-ydxnh98zwrx.ws-eu118.gitpod.io