version: '3.8'

services:
  todo-frontend:
    container_name: todo-frontend
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=https://80-niezleziolk-fullstackop-ydxnh98zwrx.ws-eu118.gitpod.io/api
    restart: always

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend-prod
    container_name: todo-backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - todo-frontend
      - todo-backend
    restart: always

volumes:
  mongo-data:
  redis-data: